name: vimes_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  data_table_2: ^2.5.10
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  intl: ^0.18.1
  money_formatter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
