// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Z-Is86fOFzs6HO7R-q3JXx0k1Zhh9Oo',
    appId: '1:433839983653:web:355c060835bea5af5103cc',
    messagingSenderId: '433839983653',
    projectId: 'vimes-test-5a783',
    authDomain: 'vimes-test-5a783.firebaseapp.com',
    storageBucket: 'vimes-test-5a783.appspot.com',
    measurementId: 'G-86RL4SFYZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbklszOTO7B9bqYMY1h5j3t1au4mdJMgU',
    appId: '1:433839983653:android:247ede52ddde87b15103cc',
    messagingSenderId: '433839983653',
    projectId: 'vimes-test-5a783',
    storageBucket: 'vimes-test-5a783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUiNCrSyVPzQ-3du-4xXtnicNracVCrEc',
    appId: '1:433839983653:ios:f21d743e36f8b7505103cc',
    messagingSenderId: '433839983653',
    projectId: 'vimes-test-5a783',
    storageBucket: 'vimes-test-5a783.appspot.com',
    iosBundleId: 'com.example.vimesTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUiNCrSyVPzQ-3du-4xXtnicNracVCrEc',
    appId: '1:433839983653:ios:6c6abaa89433b56b5103cc',
    messagingSenderId: '433839983653',
    projectId: 'vimes-test-5a783',
    storageBucket: 'vimes-test-5a783.appspot.com',
    iosBundleId: 'com.example.vimesTest.RunnerTests',
  );
}
